import { notFound } from "next/navigation";
import { requireOrgContext } from "@/lib/org";
import { age, fileNo, fullName } from "@/lib/format";
import { PrintButton } from "./print-button";

type RxItem = { drug: string; dose: string; frequency: string; duration: string };

/** Printable prescription — browser print produces the PDF. */
export default async function PrescriptionPrintPage({
  params,
}: {
  params: Promise<{ rxId: string }>;
}) {
  const { db, organization } = await requireOrgContext();
  const { rxId } = await params;

  const rx = await db.prescription.findUnique({
    where: { id: rxId },
    include: {
      patient: true,
      provider: { include: { membership: { include: { user: true } } } },
    },
  });
  if (!rx) notFound();

  const clinic = await db.clinic.findFirst({ where: { isActive: true }, orderBy: { createdAt: "asc" } });
  const items = (rx.items as RxItem[]) ?? [];
  const provider = rx.provider;

  return (
    <main className="mx-auto max-w-2xl bg-white p-10 text-gray-900 print:p-0">
      <div className="mb-4 flex justify-end print:hidden">
        <PrintButton />
      </div>

      <header className="border-b-2 border-gray-800 pb-4">
        <h1 className="text-2xl font-bold">{organization.name}</h1>
        <p className="text-sm text-gray-600">
          {clinic?.name}
          {clinic?.address ? ` · ${clinic.address}` : ""}
          {clinic?.phone ? ` · ${clinic.phone}` : ""}
        </p>
      </header>

      <section className="mt-6 grid grid-cols-2 gap-y-1 text-sm">
        <div>
          <span className="text-gray-500">Patient: </span>
          <span className="font-semibold">{fullName(rx.patient)}</span>{" "}
          <span className="text-gray-400">{fileNo(rx.patient.fileNumber)}</span>
        </div>
        <div className="text-right">
          <span className="text-gray-500">Date: </span>
          <span className="font-semibold">{rx.issuedAt.toISOString().slice(0, 10)}</span>
        </div>
        <div>
          <span className="text-gray-500">Age: </span>
          {age(rx.patient.dob) ?? "—"}
        </div>
        <div className="text-right">
          <span className="text-gray-500">CPR: </span>
          {rx.patient.cpr ?? "—"}
        </div>
      </section>

      <div className="mt-8">
        <div className="text-4xl font-serif italic text-gray-800">℞</div>
        <ol className="mt-4 space-y-4 border-l-2 border-gray-200 pl-5">
          {items.map((it, i) => (
            <li key={i} className="text-base">
              <div className="font-semibold">{it.drug}</div>
              <div className="text-sm text-gray-700">
                {[it.dose, it.frequency, it.duration && `for ${it.duration}`]
                  .filter(Boolean)
                  .join(" · ")}
              </div>
            </li>
          ))}
        </ol>
        {rx.notes && (
          <p className="mt-6 rounded-md bg-gray-50 px-3 py-2 text-sm text-gray-700 print:border print:border-gray-300">
            {rx.notes}
          </p>
        )}
      </div>

      <footer className="mt-16 flex items-end justify-between text-sm">
        <div className="text-gray-500">
          Generated by DentalOS · {new Date().toISOString().slice(0, 10)}
        </div>
        <div className="text-center">
          <div className="mb-10 border-b border-gray-400 pb-1" style={{ minWidth: 200 }} />
          <div className="font-semibold">
            {provider.title ? `${provider.title} ` : ""}
            {provider.membership.user.name}
          </div>
          {provider.nhraLicenseNo && (
            <div className="text-xs text-gray-500">NHRA license {provider.nhraLicenseNo}</div>
          )}
        </div>
      </footer>
    </main>
  );
}
